name: Firebase Hosting Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to Firebase Hosting
        uses: firebase/firebase-hosting-deploy@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          firebase-project-id: ${{ secrets.FIREBASE_PROJECT_ID }}
          hosting-config: firebase.json
          dir: .
