name: Firebase Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 127.0.0.1:2375:2375
        env:
          DOCKER_HOST: tcp://127.0.0.1:2375
          DOCKER_TLS_VERIFY: 0

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./functions

    - name: Build functions
      run: npm run build
      working-directory: ./functions

    - name: Run tests
      run: npm test
      working-directory: ./functions

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase deploy --only functions
      working-directory: ./functions
